<?php
$message = '';
if (!empty($_SESSION['message'])) {
    $message = join('<br />', $_SESSION['message']['text']);
    $messageStyle = $_SESSION['message']['type'];
    unset($_SESSION['message']);
}
?>
<style>
    #edit_dialog label{
        width:170px;
        float: left;
    }
    #edit_dialog input,#edit_dialog textarea{
        width:310px;
    }
    .error {
        background-color: #FCC;
    }

    #edit_form div{
        padding-bottom: 5px;
    }

    hr{
        border: 0;
        background-color:  #A6C9E2;
        height: 1px;
    }

    .ui-icon-cancel, .ui-icon-close {
        cursor: pointer;
    }
</style>
<div class="content">
    <?php if (!empty($message)) : ?>
        <div class="message <?php echo $messageStyle; ?>" >
            <?php echo $message; ?>                
        </div>
    <?php endif; ?>

    <div>
        <form id="date_form">
            <input type="hidden" name="cont" value="stat">
            <input type="hidden" name="act" value="stat">
            <label for="start">Start date: </label>
            <select id="start" name="start">
                <?php foreach ($dates as $date): ?>
                    <option value="<?php echo $date; ?>" <?php if ($date == $start) echo 'selected="selected"'; ?>><?php echo $date; ?></option>
                <?php endforeach; ?>
            </select>
            <label for="end">End date: </label>
            <select id="end" name="end">
                <?php foreach ($dates as $date): ?>
                    <option value="<?php echo $date; ?>" <?php if ($date == $end) echo 'selected="selected"'; ?>><?php echo $date; ?></option>
                <?php endforeach; ?>
            </select>
            <label for="end">Campaign name: </label>
            <select id="campaign_id" name="campaign_id">
                <option value="-1">Summary</option>
                <?php foreach ($campaigns as $campaign): ?>
                    <option value="<?php echo $campaign['id']; ?>" <?php if ($campaign_id == $campaign['id']) echo 'selected="selected"'; ?>><?php echo $campaign['name']; ?></option>
                <?php endforeach; ?>
            </select>
            <input type="submit" name="submit" value="refresh">
        </form>
    </div>

    <table id="table1" class="display" >
        <thead>
            <tr>
                <th>Day</th>
                <th>Redirect</th>
                <th>Exception</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>