<div class="content">

    <div style="text-align: center; font-size: 21px; margin-bottom: 12px;">
        Advertisers with equal C/T URLs
    </div>
    <div class="multi_set">
        <input type="checkbox" id="check_all"/>
        <span>Set as</span>
        <select>
            <option value="article">article</option>
            <option value="placeholder">placeholder</option>
        </select>
        <input type="button" id="set_checked_role" value="SET"/>
    </div>
    <table id="equal_table" class="display" >
        <thead>
            <tr>
                <th style="padding:0"></th>
                <th>Parametrized URL</th>
                <th>Advertiser</th>
                <th>Competitor URL</th>
                <th>Tracking URL</th>
                <th style="">Actions</th>
                <th style="">Set as:</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>