<div class="content">
    
    <div style ="margin-left: 10px;">
        <div style="margin:10px 0;">
            <a href="index.php?cont=troubleshooting&act=equalurls" >1. Advertisers with equal C/T URLs</a>
        </div>
        <div style="margin:10px 0;">
            <a href="index.php?cont=troubleshooting&act=missingurls" >2. Missing advertiser URL's</a>
        </div>
        <div style="margin:10px 0;">
            <a href="index.php?cont=troubleshooting&act=ipsforblacklists" >3. IP's for blacklists</a>
        </div>
        <div style="margin:10px 0;">
            <a href="index.php?cont=troubleshooting&act=duplication" >4. Duplication of posts</a>
        </div>        
    </div>    
    
</div>